// require('prismjs/plugins/line-numbers/prism-line-numbers.css');
// require('prismjs/themes/prism-dark.min.css');
require('prismjs/themes/prism.min.css');
// require('prismjs/components/index');
require('prismjs/plugins/autolinker/prism-autolinker.css');
require('prismjs/plugins/autoloader/prism-autoloader.js');
require('prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.js');
require('prismjs/plugins/line-numbers/prism-line-numbers.css');
require('prismjs/plugins/command-line/prism-command-line.css');
require('./globals.css');
